# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Vt2wxADGOHmuK-K5GWKFvzIReRBVqMwL
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/Data (2).csv')

df.head(10)

df.tail(20)

df.info()

df.describe()

a=df['Age']
plt.plot(a)

b=df['Country']
c=df['Salary']
plt.scatter(b,c)

d=df['Age']
plt.hist(d)

e=df['Country']
plt.bar(e,width=100,height=100)

A=df['Age']
B=df['Purchased']
sns.lineplot(x=A,y=B,data=df)

C=df['Age']
D=df['Purchased']
sns.scatterplot(x=C,y=D,data=df)

E=df['Age']
F=df['Purchased']
sns.barplot(x=E,y=F,data=df)

sns.countplot(x='Age',data=df)

sns.pairplot(df,hue='Country')

df.isnull().sum()

df.isna().sum()

import missingno as msno

msno.bar(df)
plt.show

df['Age']=df['Age'].fillna(df['Age'].mode()[0])

df

df['Salary']=df['Salary'].fillna(df['Salary'].mode()[0])

df

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

a=df['Country']

df['Country']=le.fit_transform(a)

df

pd.get_dummies(df)

a=df.iloc[ 0:-1 , 1:3]
a

b=df.iloc[: , :4]
b

df['Age'].nunique()

df['Age'].unique()